[SUP-6256] Only use content sync normalizers for content sync processes
discoverygarden/content_sync pull request #16
Opened 2023-12-08 17:38 UTC by JojoVes

Without this flagging in place, the content sync normalizer was firing for everything and cleaning entity IDs out of places like rest endpoints used to get entities as json.

2023-12-08 19:43 UTC, adam-vessey requested changes, later dismissed

2023-12-08 19:43 UTC, adam-vessey commented on src/Exporter/ContentExporter.php
> +    $entity->is_content_sync = TRUE;
Dynamic properties are deprecated in PHP 8.2. Given the flag in `$context`, can probably just make use of it?...

2023-12-08 19:43 UTC, adam-vessey commented on src/Normalizer/ContentEntityNormalizer.php
> +    return parent::supportsNormalization($data, $format, $context) && !empty($data->is_content_sync);
As in:

```suggestion
    return parent::supportsNormalization($data, $format, $context) && ($context['content_sync'] ?? FALSE);
```

2023-12-13 18:07 UTC, nhart approved these changes

2024-01-04 18:14 UTC, merged